### ISSUE TITLE
cargo-binutils dependency

### ISSUE THREAD

**Issue by Geens** [matteocarnelos/arduino-run#1]
Wow, this worked surprisingly well! Thank you so much for creating this wrapper.

I noticed the installation section of the readme don't mention cargo-binutils and its requirement llvm-tools-preview. It took me some time to figure that out because the error message simply says "program not found"

Can you maybe add these to the readme?
$ cargo install cargo-binutils
$ rustup component add llvm-tools-preview

**Comment by matteocarnelos** [comment]
Thanks for the catch! I had that crate already installed and I forgot that it was needed. I'll add it in the README.
